version: "3.8"
services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postq
      POSTGRES_USER: postq
      POSTGRES_PASSWORD: postq
    volumes:
      - pgdata:/var/lib/postgresql/data

  postq:
    depends_on: 
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: ['-s', '5', '-e', 'docker'] # sleep max 5 sec., use docker executor, default qname=''
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DEBUG: "True"
      DATABASE_URL: "postgresql://postq:postq@postgres/postq"
      TMPDIR: /tmp/

volumes: 
  pgdata:

