version: "3.7"
services:

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: postq
      POSTGRES_USER: postq
      POSTGRES_PASSWORD: postq
    volumes:
      - pgdata:/var/lib/postgresql/data

  postq:
    depends_on: 
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DEBUG: "True"

      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      POSTGRES_HOST: postgres
      POSTGRES_DB: postq
      POSTGRES_USER: postq
      POSTGRES_PASSWORD: postq

      POSTQ_QNAME: q

volumes: 
  pgdata:

