"""job

Revision ID: 91909b736587
Revises: 7e8956a72cf2
Create Date: 2020-08-22 23:15:48.639507+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '91909b736587'
down_revision = '7e8956a72cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'job',
        sa.Column(
            'id',
            postgresql.UUID(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column('qname', sa.String(), nullable=True),
        sa.Column(
            'retries', sa.SmallInteger(), server_default=sa.text('1'), nullable=True
        ),
        sa.Column(
            'queued',
            sa.DateTime(timezone=True),
            server_default=sa.text('current_timestamp'),
            nullable=False,
        ),
        sa.Column(
            'scheduled',
            sa.DateTime(timezone=True),
            server_default=sa.text('current_timestamp'),
            nullable=False,
        ),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column(
            'tasks',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            'data',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='postq',
    )
    op.create_table(
        'job_log',
        sa.Column('id', postgresql.UUID(), nullable=True),
        sa.Column('qname', sa.String(), nullable=True),
        sa.Column('retries', sa.SmallInteger(), nullable=True),
        sa.Column('queued', sa.DateTime(timezone=True), nullable=False),
        sa.Column('scheduled', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column(
            'logged',
            sa.DateTime(timezone=True),
            server_default=sa.text('current_timestamp'),
            nullable=False,
        ),
        sa.Column(
            'tasks',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            'data',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            'errors',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        schema='postq',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_log', schema='postq')
    op.drop_table('job', schema='postq')
    # ### end Alembic commands ###
