"""job_log

Revision ID: b76f56db845a
Revises: 7e8956a72cf2
Create Date: 2020-09-05 19:48:20.702598+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b76f56db845a'
down_revision = '7e8956a72cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'job',
        sa.Column(
            'id',
            postgresql.UUID(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column('qname', sa.String(), nullable=False),
        sa.Column(
            'retries', sa.SmallInteger(), server_default=sa.text('1'), nullable=True
        ),
        sa.Column(
            'queued',
            sa.DateTime(timezone=True),
            server_default=sa.text('current_timestamp'),
            nullable=False,
        ),
        sa.Column(
            'scheduled',
            sa.DateTime(timezone=True),
            server_default=sa.text('current_timestamp'),
            nullable=False,
        ),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column(
            'workflow',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            'data',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='postq',
    )
    op.create_index(
        op.f('ix_postq_job_qname'), 'job', ['qname'], unique=False, schema='postq'
    )
    op.create_index(
        op.f('ix_postq_job_queued'), 'job', ['queued'], unique=False, schema='postq'
    )
    op.create_index(
        op.f('ix_postq_job_retries'), 'job', ['retries'], unique=False, schema='postq'
    )
    op.create_table(
        'job_log',
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.Column('qname', sa.String(), nullable=False),
        sa.Column('retries', sa.SmallInteger(), nullable=True),
        sa.Column('queued', sa.DateTime(timezone=True), nullable=False),
        sa.Column('scheduled', sa.DateTime(timezone=True), nullable=False),
        sa.Column('initialized', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'logged',
            sa.DateTime(timezone=True),
            server_default=sa.text('current_timestamp'),
            nullable=False,
        ),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column(
            'workflow',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            'data',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        schema='postq',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_log', schema='postq')
    op.drop_index(op.f('ix_postq_job_retries'), table_name='job', schema='postq')
    op.drop_index(op.f('ix_postq_job_queued'), table_name='job', schema='postq')
    op.drop_index(op.f('ix_postq_job_qname'), table_name='job', schema='postq')
    op.drop_table('job', schema='postq')
    # ### end Alembic commands ###
